# Nombre del Workflow para identificarlo en la pestaña "Actions" de GitHub
name: Deploy to GitHub Pages

on:
  # Se ejecuta en cada push a la rama 'main'
  push:
    branches:
      - main

  # Permite ejecutar este workflow manualmente desde la pestaña Actions
  workflow_dispatch:

# Configura los permisos para que el workflow pueda desplegar en GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Match your prerequisite
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      #  Ejecutar Tests (Add this if you have tests)
      # - name: Run Unit Tests
      #   run: npm test

      - name: Build Project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
